env: "local" # local, dev, prod
database_url: "host=localhost port=5432 user=app password=p@ssw0rd dbname=url_shortener_dev sslmode=disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
